msm8937-common: hw-qcom-camera: Completed FR49059 and FR49058
FR49059: Accessing AOSP/Google projects Headers

Description: Vendor modules cannot refer AOSP header
paths with absolute or Global Paths instead add
corresponding header library

FR49058 :  VNDK compliance

Description : VNDK is set of AOSP libraries which
are exposed to vendor (partition) for development.

Example :

error: vendor lib "/vendor/lib/libeffects.so"
 depends on non-eligible lib
 "/system/lib/libeffectsconfig.so".
Here , QCOM vendor-partition Library
using lib outside VNDK from system.

CRs-Fixed: 2217547

Change-Id: I51a88145fccba592080d6287ae7ff14d12c65296